name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', 8.1]
        laravel: ['8.*', '9.*', '10.*']
        include:
          - php: '8.0'
            laravel: '8.*'
            testbench: '6.*'
          - php: '8.0'
            laravel: '9.*'
            testbench: '7.*'
          - php: 8.1
            laravel: '9.*'
            testbench: '7.*'
          - php: 8.1
            laravel: '10.*'
            testbench: '8.*'
        exclude:
          - php: '8.0'
            laravel: '10.*'
          - php: '8.1'
            laravel: '8.*'

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
        coverage: pcov

    - uses: actions/cache@v3.0.11
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: |
        CACHE_DRIVER=array vendor/bin/phpunit --coverage-text --coverage-clover=coverage_array.xml
        CACHE_DRIVER=file vendor/bin/phpunit --coverage-text --coverage-clover=coverage_file.xml

    - uses: codecov/codecov-action@v3.1.1
      with:
        fail_ci_if_error: false
        file: '*.xml'
